version: '3.7'

services:
  mysqlsrv:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/docker/mysql/volumes:/var/lib/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge